CP Code Import
akamai/terraform-provider-akamai pull request #110
Opened 2020-02-26 19:15 UTC by joel-g

Adds Import function to CP Code resource.

Usage:

```
terraform import akamai_cp_code.foo cpc_123456:ctr_123456:grp_123456
```

All three IDs are required and must be in order delimeted with colons.

Also updates documentation to reflect new functionality.

2020-03-04 16:32 UTC, joel-g commented
@edglynes @martinstibbe can we get this reviewed?

2021-08-24 09:38 UTC, robertolopezlopez requested changes
Hi @joel-g ,

Thank you for creating this PR :-)

Several suggestions:

* As convention, we use the comma character (`,`) as separator in the import ID.
* Please, rebase your PR to solve merge conflicts.
* Please, add unit tests.
* And finally, please squash all your commits :-)

Cheers,

Roberto

2021-08-24 09:38 UTC, robertolopezlopez commented on akamai/resource_akamai_cp_code.go
> +	}
As convention, we use the comma character (`,`) as separator in the import ID.

```suggestion
	args := strings.Split(id, ",")
	if len(args) != 3 {
		return nil, fmt.Errorf("Akamai CP Code import requires CP Code ID, Contract ID and Group ID delimited by ','. Received %s", id)
	}
```

2021-08-24 09:38 UTC, robertolopezlopez commented on akamai/resource_akamai_cp_code.go
> +		return nil, fmt.Errorf("Akamai CP Code import requires CP Code ID (cpc_xxxxx) as first ':' delimited argument. Received %s", cpCodeID)
```suggestion
		return nil, fmt.Errorf("Akamai CP Code import requires CP Code ID (cpc_xxxxx) as first ',' delimited argument. Received %s", cpCodeID)
```

2021-08-24 09:38 UTC, robertolopezlopez commented on akamai/resource_akamai_cp_code.go
> +		return nil, fmt.Errorf("Akamai CP Code import requires Contract ID (ctr_xxxxx) as second ':' delimited argument. Received %s", contractID)
```suggestion
		return nil, fmt.Errorf("Akamai CP Code import requires Contract ID (ctr_xxxxx) as second ',' delimited argument. Received %s", contractID)
```

2021-08-24 09:38 UTC, robertolopezlopez commented on akamai/resource_akamai_cp_code.go
> +		return nil, fmt.Errorf("Akamai CP Code import requires Group ID (grp_xxxxx) as third ':' delimited argument. Received %s", groupID)
```suggestion
		return nil, fmt.Errorf("Akamai CP Code import requires Group ID (grp_xxxxx) as third ',' delimited argument. Received %s", groupID)
```

2021-08-24 09:38 UTC, robertolopezlopez commented on website/docs/r/cp_code.html.markdown
> +terraform import akamai_cp_code.foo cpc_123456:ctr_123456:grp_123456
```suggestion
terraform import akamai_cp_code.foo cpc_123456,ctr_123456,grp_123456
```

2021-08-24 11:48 UTC, closed without merging